### ISSUE TITLE
Command line options do not work

### ISSUE THREAD

**Issue by gorank115** [jesseditson/node-caption#1]
I've tried the command line options including the one you provided using Judge Dread, and it just keeps providing the usage criteria.

**Comment by humanman** [comment]
I'm having the same problem, and when I try doing it in Node, it says the CaptionImage in the callback is undefined.

**Comment by jesseditson** [comment]
Just pushed an update (v0.1.1) that should resolve this issue - let me know if there are any issues! The API changed a little, parameters are now named and not ordered (except the filename).
