### ISSUE TITLE
 [Error: Invalid Path to image] is caption param empty

### ISSUE THREAD

**Issue by wclr** [jesseditson/node-caption#2]
[Error: Invalid Path to image] is caption param empty (maybe only bottomCaption is needed.)

**Comment by jesseditson** [comment]
Hello! Could you possibly expand on the issue you're having?

Are you using this library programatically or via the command line?

What were the steps you took to get this issue?

I've recently updated the README of this repo, it may be worth reading the new docs and trying again!
