### ISSUE TITLE
Font cut off with all caps

### ISSUE THREAD

**Issue by zackify** [jesseditson/node-caption#3]
When you use all caps or have long text, it gets chopped off, also would like to be able to change the font  itself

**Comment by ghost** [comment]
@zackify I also want to change the font myself. I'm guessing u need to expose the font method.

In imagemagick, the font method is `-font` (based on [this](http://www.imagemagick.org/Usage/fonts/))
So probably to add custom font, we gotta add a line like [this one](https://github.com/jesseditson/node-caption/blob/master/lib/generate.js#L68) for font. @jesseditson is that right?

**Comment by jesseditson** [comment]
@tUrG0n Yup, that looks correct - it'll probably want a default value as well, [something like this](https://github.com/jesseditson/node-caption/blob/master/lib/generate.js#L50)

**Comment by ghost** [comment]
@jesseditson awesome thx :)
