### ISSUE TITLE
"ImageMagick is not installed" when it is.

### ISSUE THREAD

**Issue by Tvde1** [jesseditson/node-caption#6]
I keep getting 
```
                        if (err) throw err;
                                 ^

Error: ImageMagick not installed.
    at D:\[path]\node_modules\caption\lib\generate.js:22:50
```

While ImageMagick is installed:
If I do `npm list`, I get
```
+-- imagemagick@0.1.3
```
Any fix?

**Comment by jesseditson** [comment]
The missing ImageMagick is the imagemagick binary, not the node module (which just uses the global binary). At the top of the [REAMDE](https://github.com/jesseditson/node-caption/blob/master/README.md) there are instructions on installing on *nix systems, but it looks like you're trying to run on windows.

Unfortunately I have no experience installing on windows, but here's a SO question that may help point you in the right direction: http://stackoverflow.com/questions/3036847/how-to-install-imagemagick-on-windows-7

As far as I can tell the `node-caption` lib is working as expected, but if you find a path forward on windows, a documentation PR would be gladly accepted!
